version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: task_db
    restart: always
    environment:
      POSTGRES_DB: task_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d task_management"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task_api
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:123456@localhost:5432/task_management
      LOG_LEVEL: INFO
      JWT_SECRET: your-super-secret-key-here-change-in-production
      JWT_ALGORITHM: HS256
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

volumes:
  db_data:
